version: '3.8'

services:
    enb_mono_tdd:
        image: oai-enb:latest
        privileged: true
        container_name: lte-b200-enb-tdd-20Mhz-tm1
        environment:
            USE_B2XX: 'yes'
            USE_ADDITIONAL_OPTIONS: --RUs.[0].max_rxgain 115 --eNBs.[0].component_carriers.[0].pdsch_referenceSignalPower -29 --MACRLCs.[0].scheduler_mode default --log_config.global_log_options level,nocolor,time,line_num,function
        volumes:
            - ../../conf_files/enb.band40.100prb.usrpb200.tm1-defaultscheduler.conf:/opt/oai-enb/etc/enb.conf
            - /dev:/dev
        network_mode: "host"
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
